config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users 
  resources :posts do
    member do 
      post :favorite
      post :like
    end
    resources :responses, :controller => 'post_replies'
  	collection do
  		get :about
  	end
  end

  get '/switch' => 'users#switch'
  resources :friendships

  namespace :admin do
    resources :groups
    resources :posts do

      collection do
        post :bulk_update
      end
    end
  end

  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable ,:omniauth_providers => [:facebook, :google_oauth2]
  has_many :posts , :dependent => :destroy
  has_many :replies, :dependent => :destroy

  has_many :post_likeships
  has_many :liked_post, :through => :post_likeships, :source => :post

  has_many :user_postships, :dependent => :destroy
  has_many :fav_posts, :through => :user_postships, :source => :post

  has_many :friendships
  has_many :friends, ->{ where( "friendships.status" => "confirmed") },  :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends,->{ where( "friendships.status" => "confirmed") }, :through => :inverse_friendships, :source => :user

  include Gravtastic
  gravtastic

  def all_friends
    (friends + inverse_friends).uniq
  end

  def find_friendship(user)
    friendships.where( :friend => user ).first ||
    user.friendships.where( :friend => self ).first
  end

  def is_friend?(user)
    all_friends.include?(user)
  end

  def pending_friendship?(user)
    self.friendships.pending.where( :friend => user ).exists?
  end

  def inverse_pending_friendship?(user)
    user.friendships.pending.where( :friend => self ).exists?
  end

  def ignored_friendship?(user)
    self.friendships.ignored.where( :friend => user ).exists?
  end

  def inverse_ignored_friendship?(user)
    user.friendships.ignored.where( :friend => self ).exists?
  end




  def short_name
  	self.email.split("@").first
  end

   def admin?
    self.role == "admin"
   end

  def liked_post?(post)
    self.liked_post.include?(post)
  end

  def faved_post?(post)
    self.fav_posts.include?(post)
  end

  def self.from_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      #existing_user.fb_raw_data = auth
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.nickname = auth.info.name
    user.password = Devise.friendly_token[0,20]
    #user.fb_raw_data = auth
    user.save!
    return user
  end

  def self.from_omniauth_google(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(nickname: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20])
    end
    user
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth_google(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!


	def index 
		@users = User.all
	end

	def show
		
		@user = User.includes(:liked_post).find_by_nickname(params[:id])
	end

	def edit
		@user = User.find_by_nickname(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		if @user.update(profile_permit)
			flash[:notice]="更新成功"
			redirect_to user_path(@user.nickname)
		else
			render :action => :edit
		end
	end

	def switch
    user = User.find( params[:id] )
    reset_session
    session[:user_id] = user.id

    render :text => "this is bad"
  end




	private

	def profile_permit
		params.require(:user).permit(:about_me)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/aboutme.html.erb
<h1>你好！我是 <%= @user.nickname %></h1>

<h3>這是我的自我介紹</h3>
<p><%= simple_format @user.about_me %></p>
<br>

<table class="table table-striped">
	<tr>
		<th>
			<p>我的收藏</p>
		</th> 
		<% @user.fav_posts.each do |u| %>
	</tr>
	<tr>
		<th>
			<p><%= u.title %></p>
		</th>
	</tr>
	<% end %>
</table>

<%= link_to '編輯簡介' , edit_user_path(@user) %>
<%= link_to '回首頁' , posts_path %>

app/views/users/edit.html.erb
<%= form_for @user, :method => :patch do |f| %>

<% if @user.errors.any? %>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>
<div class="form-group col-lg-12">
	<%= f.label :about_me, "關於我" %>
	<%= f.text_field :about_me ,:class =>"form-control"%>
</div>

  <%= f.submit "送出" , :class =>"btn btn-primary"%>
<% end %>

app/views/users/index.html.erb
<h1>會員清單</h1>

<% @users.each do |u| %>
	<%= link_to u.nickname, user_path(u.nickname) %>
<% end %>

app/views/users/show.html.erb
<h1>你好！我是 <%= @user.nickname %></h1>
<br>
<%= image_tag @user.gravatar_url %>
<h3>這是我的自我介紹</h3>
<p><%= simple_format @user.about_me %></p>
<br>
<div class="row">
	<div class="col-lg-6">
		<table class="table table-striped">
			<tr>
				<th>
					<p>我的收藏</p>
				</th> 
			</tr>
			<% @user.fav_posts.each do |u| %>
			<tr>	
				<td>
					<p><%= u.title %></p>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
	<div class="col-lg-6">
		<table class="table table-striped">
			<tr>
				<th>
					<p>
						按過讚的文章
					</p>
				</th>
			</tr>
			<% @user.liked_post.each do |p| %>
			<tr>
				<td>
					<p><%= p.title %></p>
				</td>	
			</tr>
			<% end %>
		</table>
	</div>
</div>

<% if @user != current_user %>
  <p>Status:

    <% if current_user.is_friend?(@user) %>
      已經是朋友
    <% elsif current_user.pending_friendship?(@user) %>
      等待對方確認 [Remove]
    <% elsif current_user.inverse_pending_friendship?(@user) %>
      交友邀請中 [Confirm] [Ignore]
    <% elsif current_user.ignored_friendship?(@user) %>
      等待對方確認 [Remove] <- 安慰版!!
    <% elsif current_user.inverse_ignored_friendship?(@user) %>
      已被我忽略 [Confirm]
    <% else %>
      目前沒關係 <%= link_to "Request", friendships_path( :friend_id => @user), :method => :post %>
    <% end %>

  </p>
<% end %>

<h2>All friend list</h2>
<ul>
  <% @user.all_friends.each do |f| %>
    <li>
      <%= link_to f.nickname, user_path(f) %>

      <% if current_user == @user %>
        <% fs = current_user.find_friendship(f) %>
        <%= link_to "Remove", friendship_path(fs), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      <% end %>

    </li>
  <% end %>
</ul>

<% if @user == current_user %>

  <h2>Request list</h2>
    <ul>
    <% @user.friendships.pending.each do |f| %>
     <li>
        <%= link_to f.friend.nickname, user_path(f.friend) %>
        <%= link_to "Remove", friendship_path(f), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      </li>
    <% end %>
    </ul>


  <h2>Pending list</h2>

    <ul>
    <% @user.inverse_friendships.pending.each do |f| %>
     <li>
        <%= link_to f.user.nickname, user_path(f.user) %>
        <%= link_to "Confirm", friendship_path(f, :status => :confirmed), :method => :patch %>

        <%= link_to "Ignore", friendship_path(f, :status => :ignored), :method => :patch %>
      </li>
    <% end %>
    </ul>

<% end %>








<%= link_to '編輯簡介' , edit_user_path(@user.nickname) %>
<%= link_to '回首頁' , posts_path %>