config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users 
  resources :posts do
    member do 
      post :favorite
      post :like
    end
    resources :responses, :controller => 'post_replies'
  	collection do
  		get :about
  	end
  end

  get '/switch' => 'users#switch'
  resources :friendships

  namespace :admin do
    resources :groups
    resources :posts do

      collection do
        post :bulk_update
      end
    end
  end

  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user
	has_many :replies , :dependent => :destroy
	has_many :post_likeships
	has_many :users_liked, :through => :post_likeships, :source => :user

	has_many :post_groupships , :dependent => :destroy
	has_many :groups, :through => :post_groupships
	has_many :user_postships , :dependent => :destroy
	has_many :users, :through => :user_postships
	has_many :taggings
	has_many :tags, :through => :taggings

	def tag_list
		self.tags.map{ |tag| tag.name}
	end

	def tag_list=(arr)
		ids = arr.map do |tag_name|
			tag_name = tag_name.strip.downcase
			tag = Tag.find_by_name(tag_name) || Tag.create(:name => tag_name)
			tag.id
		end

		self.tag_ids = ids
	end





		
	def reply_user
		c_user =[]
      self.replies.each do |r|
        c_user << r.user.nickname
     	end
    c_user = c_user.uniq
	end

	# #Post.order
	# def self.order 
	# 	puts "class"
	# end

	# #@post.order
	# def order
	# 	puts "instance"
	# end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_user!

	before_action :check_admin 
	layout "admin"


	def index
    @users = User.all	
    @groups=Group.all
    

    if params[:id]
      @group=Group.find(params[:id])
    else
      @group=Group.new
    end

	end
  

  def bulk_update
    ids = Array( params[:ids] )
    users = ids.map{ |i| User.find_by_id(i)}.compact
    #compact把nil去除
    if  params[:commit] == "升為管理人員"
      users.each {|u| u.update(:role => "admin")}
    elsif params[:commit] == "刪除人員"
      users.each { |u| u.destroy}
    end 
    redirect_to  admin_posts_path
  end


	protected

  def check_admin
  	unless current_user.admin?
  		raise ActiceRecoed::RecordNotFound
  		return
  	end
    # authenticate_or_request_with_http_basic do |user_name, password| 很陽春的驗證流程
    #        user_name == "username" && password == "password"
    # end
  end

  def event_params
    params.require(:user).permit(:role) 
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, :only => [:show, :edit, :update, :destroy, :favorite, :like]
	before_action :authenticate_user!, :except => [:index]

	#GET posts/index
	#GET /posts
	def index
		if params[:id]
			@post = Post.find(params[:id])
		else
			@post = Post.new
		end
		
		prepare_variable_for_index_template
		
		@groups=Group.all
		
		if params[:groupid]
			# @posts = Group.find(params[:groupid]).posts.order('id ASC').page(params[:page]).per(10)
			@posts = @posts.includes(:groups).where('groups.id' => params[:groupid] )
		end

		@posts = @posts.page(params[:page]).per(10)
	end

	#GET posts/new
	def new 
		@post = Post.new
	end


  #POST /posts
	def create 
		@post = Post.new(params_permitted)
		@post.user = current_user
		if @post.save
			is_draft?
			flash[:notice]= "新增成功"
			redirect_to post_path(@post)	
		else
			render :action => :new
		end
	end

	#GET /posts/:id
	def show
		@replies = @post.replies
		@post.page_views +=  1 
		@post.save

		@reply = Reply.new
	end

	def edit
		
	end

	def update
		if params[:remove_upload_file] == "1"
      @post.image = nil
    end
		
		if @post.update(params_permitted)
			is_draft?
			flash[:notice]="編輯成功"
			redirect_to post_path(@post)
		else
			render :action => :edit
		end
	end

	def destroy
		@post.destroy
		flash[:alert] = "刪除成功"
		redirect_to posts_path
	end

	def about
		@users=User.all
		@posts=Post.all
		@replies= Reply.all
	end

	def favorite
		if current_user.faved_post?(@post)
			current_user.fav_posts.delete(@post)
		else
			current_user.fav_posts << @post
		end
    
    respond_to do |format|
    	format.html { redirect_to post_path(@post) }
    	format.js
    end
	end

	def like
		if current_user.liked_post?(@post)
			current_user.liked_post.delete(@post)
		else
			current_user.liked_post << @post
		end

		respond_to do |format|
			format.html { redirect_to post_path(@post)}
			format.js
		end
	end














	private

	def post_sort(sort_by)
	 	@posts = @posts.order(sort_by).page(params[:page]).per(10)
	end


	def set_post
		@post = Post.find(params[:id])
	end

	def params_permitted 
		params.require(:post).permit(:title, :content,:page_views,:image, {:tag_list =>[]}  ,{:group_ids => []})
	end


	def prepare_variable_for_index_template
			@posts= Post.includes(:users_liked,:replies)
		if current_user.try(:admin?)
			@posts = @posts.all
		elsif current_user
			@posts = @posts.where('user_id=? OR is_public=?', current_user.id, true)
		else
			@posts = @posts.where(:is_public => true)
		end

		case params[:order]
		when 'replies_count'
		 	sort_by = 'replies_count DESC'
		 	post_sort(sort_by)
		when 'last_replies'
		 	sort_by = 'last_replies DESC'
		 	post_sort(sort_by)
		when 'page_views'
		 	sort_by = 'page_views DESC'
		 	post_sort(sort_by)
		end	

		if params[:tag]
			tag =Tag.find_by_name(params[:tag])
			@posts = tag.posts
		end
	end

	def is_draft?
		if params[:commit] == "正式發送"
			@post.is_public = true
			@post.save
		elsif params[:commit] =="儲存草稿"
			@post.is_public =false
			@post.save
		else 
			@post.is_public = false
			@post.save
		end
	end



end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<% if @group.errors.any? %>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

	

<div class="form-group col-lg-12">
	<%= f.label :name, "群組名稱" %>
	<%= f.text_field :name   ,:class =>"form-control"%>


</div>

app/views/admin/posts/index.html.erb
<h1>This is the World of GOD!</h1>


<h3>人員清單：</h3>
<table class="table table-striped">
	<tr>
		<th></th>
		<th>暱稱</th>
		<th>信箱</th>
		<th>簡介</th>	
		<th>登入次數</th>
		<th>管理人員？</th>
		<th>編輯簡介</th>
	</tr>
<%= form_tag bulk_update_admin_posts_path do %>
	<% @users.each do |u| %>
		<tr>
			<td><%= check_box_tag "ids[]",u.id, false %></td>
			<td><%= u.nickname %></td>
			<td><%= u.email %></td>
			<td><%= u.about_me%></td>
			<td><%= u.sign_in_count%></td>
			<td><%= u.role %></td>	
			<td><%= link_to '編輯' , edit_user_path(u.nickname) %></td>
		</tr>
	<% end %>
	</table>
	<%= submit_tag "升為管理人員",:class =>"btn btn-primary"%>
	<br>
	<br>
	<%= submit_tag "刪除人員",:class =>"btn btn-primary"%>
<% end %>
<br>

<h3>依照分類</h3>
<table class="table table-striped">
	<tr>
		<td>群組名稱</td>
		<td>編輯群組名稱</td>
		<td>刪除群組</td>	
	</tr>
	<% @groups.each do |g| %>
	<tr>
	<td><%= g.name %></td>
	<td><%= link_to '編輯', admin_posts_path(:id => g)%></td>
	<td><%= link_to '刪除群組', admin_group_path(g), :method => :delete %></td>
	</tr>	
	<% end %>
</table>

<h2>快速新增</h2>
<%= form_for [:admin, @group]  do |f| %>
	<%= render :partial => "form", :locals => {:f => f} %>
	<%= f.submit "新增/修改" , :class =>"btn btn-primary"%>
<% end %>