config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users 
  resources :posts do
    member do 
      post :favorite
      post :like
    end
    resources :responses, :controller => 'post_replies'
  	collection do
  		get :about
  	end
  end

  get '/switch' => 'users#switch'
  resources :friendships

  namespace :admin do
    resources :groups
    resources :posts do

      collection do
        post :bulk_update
      end
    end
  end

  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user
	has_many :replies , :dependent => :destroy
	has_many :post_likeships
	has_many :users_liked, :through => :post_likeships, :source => :user

	has_many :post_groupships , :dependent => :destroy
	has_many :groups, :through => :post_groupships
	has_many :user_postships , :dependent => :destroy
	has_many :users, :through => :user_postships
	has_many :taggings
	has_many :tags, :through => :taggings

	def tag_list
		self.tags.map{ |tag| tag.name}
	end

	def tag_list=(arr)
		ids = arr.map do |tag_name|
			tag_name = tag_name.strip.downcase
			tag = Tag.find_by_name(tag_name) || Tag.create(:name => tag_name)
			tag.id
		end

		self.tag_ids = ids
	end





		
	def reply_user
		c_user =[]
      self.replies.each do |r|
        c_user << r.user.nickname
     	end
    c_user = c_user.uniq
	end

	# #Post.order
	# def self.order 
	# 	puts "class"
	# end

	# #@post.order
	# def order
	# 	puts "instance"
	# end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_user!

	before_action :check_admin 
	layout "admin"


	def index
    @users = User.all	
    @groups=Group.all
    

    if params[:id]
      @group=Group.find(params[:id])
    else
      @group=Group.new
    end

	end
  

  def bulk_update
    ids = Array( params[:ids] )
    users = ids.map{ |i| User.find_by_id(i)}.compact
    #compact把nil去除
    if  params[:commit] == "升為管理人員"
      users.each {|u| u.update(:role => "admin")}
    elsif params[:commit] == "刪除人員"
      users.each { |u| u.destroy}
    end 
    redirect_to  admin_posts_path
  end


	protected

  def check_admin
  	unless current_user.admin?
  		raise ActiceRecoed::RecordNotFound
  		return
  	end
    # authenticate_or_request_with_http_basic do |user_name, password| 很陽春的驗證流程
    #        user_name == "username" && password == "password"
    # end
  end

  def event_params
    params.require(:user).permit(:role) 
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, :only => [:show, :edit, :update, :destroy, :favorite, :like]
	before_action :authenticate_user!, :except => [:index]

	#GET posts/index
	#GET /posts
	def index
		if params[:id]
			@post = Post.find(params[:id])
		else
			@post = Post.new
		end
		
		prepare_variable_for_index_template
		
		@groups=Group.all
		
		if params[:groupid]
			# @posts = Group.find(params[:groupid]).posts.order('id ASC').page(params[:page]).per(10)
			@posts = @posts.includes(:groups).where('groups.id' => params[:groupid] )
		end

		@posts = @posts.page(params[:page]).per(10)
	end

	#GET posts/new
	def new 
		@post = Post.new
	end


  #POST /posts
	def create 
		@post = Post.new(params_permitted)
		@post.user = current_user
		if @post.save
			is_draft?
			flash[:notice]= "新增成功"
			redirect_to post_path(@post)	
		else
			render :action => :new
		end
	end

	#GET /posts/:id
	def show
		@replies = @post.replies
		@post.page_views +=  1 
		@post.save

		@reply = Reply.new
	end

	def edit
		
	end

	def update
		if params[:remove_upload_file] == "1"
      @post.image = nil
    end
		
		if @post.update(params_permitted)
			is_draft?
			flash[:notice]="編輯成功"
			redirect_to post_path(@post)
		else
			render :action => :edit
		end
	end

	def destroy
		@post.destroy
		flash[:alert] = "刪除成功"
		redirect_to posts_path
	end

	def about
		@users=User.all
		@posts=Post.all
		@replies= Reply.all
	end

	def favorite
		if current_user.faved_post?(@post)
			current_user.fav_posts.delete(@post)
		else
			current_user.fav_posts << @post
		end
    
    respond_to do |format|
    	format.html { redirect_to post_path(@post) }
    	format.js
    end
	end

	def like
		if current_user.liked_post?(@post)
			current_user.liked_post.delete(@post)
		else
			current_user.liked_post << @post
		end

		respond_to do |format|
			format.html { redirect_to post_path(@post)}
			format.js
		end
	end














	private

	def post_sort(sort_by)
	 	@posts = @posts.order(sort_by).page(params[:page]).per(10)
	end


	def set_post
		@post = Post.find(params[:id])
	end

	def params_permitted 
		params.require(:post).permit(:title, :content,:page_views,:image, {:tag_list =>[]}  ,{:group_ids => []})
	end


	def prepare_variable_for_index_template
			@posts= Post.includes(:users_liked,:replies)
		if current_user.try(:admin?)
			@posts = @posts.all
		elsif current_user
			@posts = @posts.where('user_id=? OR is_public=?', current_user.id, true)
		else
			@posts = @posts.where(:is_public => true)
		end

		case params[:order]
		when 'replies_count'
		 	sort_by = 'replies_count DESC'
		 	post_sort(sort_by)
		when 'last_replies'
		 	sort_by = 'last_replies DESC'
		 	post_sort(sort_by)
		when 'page_views'
		 	sort_by = 'page_views DESC'
		 	post_sort(sort_by)
		end	

		if params[:tag]
			tag =Tag.find_by_name(params[:tag])
			@posts = tag.posts
		end
	end

	def is_draft?
		if params[:commit] == "正式發送"
			@post.is_public = true
			@post.save
		elsif params[:commit] =="儲存草稿"
			@post.is_public =false
			@post.save
		else 
			@post.is_public = false
			@post.save
		end
	end



end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_favorite.html.erb
<% if current_user.faved_post?(@post) %>
	<%= button_to "取消訂閱" , favorite_post_path(@post),:class =>"btn btn-primary", :remote =>true %>
<% else %>
	<%= button_to "訂閱" , favorite_post_path(@post),:class =>"btn btn-primary", :remote =>true %>
<% end %>

app/views/posts/_form.html.erb
<div class="form-group col-lg-12">
	<%= f.label :title, "標題" %>
	<%= f.text_field :title ,:class =>"form-control"%>
</div>
<div class="form-group col-lg-12">
 <%= f.collection_check_boxes :group_ids, Group.all, :id, :name, :class => "group" %>
</div>
<div class="form-group col-lg-12">
	<%= f.label :content, "內文"%>
	<%= f.text_area :content ,:class =>"form-control"%>
</div>

<div class="from-group col-lg-12">
	<%= f.label :tag_list, "標籤"%>
	<%= f.select :tag_list, Tag.all.map{ |x| [x.name, x.name] },{},{:multiple => true,:class =>"form-control"}%>
	<%#= f.text_field :tag_list ,:class =>"form-control"%>
</div>
<div class="form-group col-lg-12">
	<%= f.file_field :image %>
	<% if @post.image.exists? %>
  	<%= check_box_tag "remove_upload_file", "1" %>移除上傳檔案
	<% end %>
</div>



<script>
  $("#post_tag_list").select2({
    tags: true
  });
</script>

app/views/posts/_likepost.html.erb
<% if current_user.liked_post?(@post) %>
	<%= button_to "取消讚" , like_post_path(@post), :remote =>true, :class =>"btn btn-primary" %>
<% else %>
	<%= button_to "讚" , like_post_path(@post), :remote =>true, :class =>"btn btn-primary" %>
<% end %>

app/views/posts/about.html.erb
<h1>HI!</h1>

<h2>本站有 <%= @posts.count %> 個主題 </h2>
<h2>共有 <%= @users.count %> 個使用者 </h2>
<h2>共有 <%= @replies.count %> 則回覆 </h2>

<%= link_to '回首頁' , posts_path %>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	      <ul>
	      <% @post.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	<% end %>

		<%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "正式發送" , :class =>"btn btn-primary"%>
    <%= f.submit "改為草稿" , :class =>"btn btn-primary"%>
    <%= f.submit "儲存草稿" , :class =>"btn btn-primary"%>
<% end %>

app/views/posts/favorite.js.erb
<% if current_user.faved_post?(@post) %>
	$('.fav-post input[type=submit]').val("取消訂閱");
<% else %>
	$('.fav-post input[type=submit]').val("訂閱");
<% end %>

app/views/posts/index.html.erb
<h1><%= link_to 'Swingcloud Forum' , posts_path%> </h1>
	<div class="sort">
		<div class="pull-left">
			<%= link_to  new_post_path do %>
				<i class='icon-pencil'></i>新增文章
			<% end %>
		</div>
		<div class="pull-right">
			<%= link_to '依照回覆數排列', posts_path( :order => "replies_count") %>
			<%= link_to '依照最後回覆時間', posts_path( :order => "last_replies") %>
			<%= link_to '依照瀏覽數進行排序', posts_path( :order => "page_views") %>
			<%= link_to '原排列', posts_path %>
		</div>
	</div>
	<div class="clearfix sort-opt"></div>

<table class="table table-striped">
	<tr>
		<th>標題</th>
		<th>作者</th>
		<th>回應數</th>
		<th>瀏覽數</th>
		<th>參與討論</th>
		<th>誰按過讚？</th>
		<th>標籤</th>
		<th></th>
		<th></th>
	</tr>
	<% @posts.each do |p| %>
	<tr>
		<td><h3><%= link_to p.title, post_path(p) %></h3></td>
		<td><h3><%=link_to  p.user.nickname, user_path(p.user.nickname) %></h3></td>
		<td><%= p.replies.count %></td>
		<td><%= p.page_views %></td>
		<td>
			<% p.reply_user.each do |u| %>
        <p><%= u %></p>
      <%end%>
		</td>
		<td>
			<% p.users_liked.each do |l| %>
				<p style="border: 1px solid navy; background-color: #02ABD6; color:white; text-align:center; border-radius:5px"><%= l.nickname %></p>
			<% end %>
		</td>
		<td>
			<% p.tags.each do |t| %>
				<%= link_to t.name, posts_path(:tag => t.name) %>
			<% end %>
		</td>	
		<% if current_user == p.user || current_user.try(:admin?) %>
			<td>
				<%= link_to  edit_post_path(p) do %>
					<i class='icon-pencil'></i>編輯
				<% end %>
			</td>
		<% end %>
		<% if current_user == p.user || current_user.try(:admin?) %>
			<td>
				<%= link_to post_path(p), :method => :delete do%>
					<i class='icon-trash'></i>刪除
					<% end %>
			</td>
		<% end %>
	<% end %>
	</tr>
</table>
<%= paginate @posts %>
<br>
<h3>依照分類</h3>
	<% @groups.each do |g| %>
	<%= link_to g.name, posts_path(:groupid => g, :order => params[:order]) %>
	<% end %>

	<%= form_tag posts_path, :class => "form-inline", :method => :get do %>
	<div class="form-group">
		<%= select_tag :groupid, options_for_select(Group.all.map{|g| [g.name , g.id]},params[:groupid]), :class => "form-control group-form"  %>
	</div>
	<%= submit_tag "Go!" , :class => "btn btn-default"%> 
	<%end%>
	

	
<h2>快速新增</h2>
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
	<% end %>
	<%= render :partial => "form", :locals => {:f => f} %>
	<%= f.submit "送出" , :class =>"btn btn-primary"%>
<% end %>

app/views/posts/like.js.erb
<% if current_user.liked_post?(@post) %>
	$('.like input[type=submit]').val("取消讚");
<% else %>
	$('.like input[type=submit]').val("讚");
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
	<% end %>

		<%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "正式發送" , :class =>"btn btn-primary"%>
    <%= f.submit "儲存草稿" , :class =>"btn btn-primary"%>
<% end %>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<h1>
			<%= @post.title %>
		</h1>
		<% @post.groups.each do |g| %>
			<li>
			<%= g.name %>
			</li>
		<% end %>
			<p class="col-lg-12">
				<%= simple_format @post.content %>
			</p>
			<% if @post.image.exists? %>
				<div>
					<%= image_tag @post.image.url(:medium) %>	
				</div>
			<% end %>
			<div class="like">
				<%= render :partial => 'likepost' %>
			</div>
		<table class="table table-striped replies-list"">
			<p>回應數：<%=@replies.count%></p>
			<tr>
				<td class="col-lg-2">評論人</td>
				<td class="col-lg-9">內容</td>
				<td class="col-lg-1"></td>
			</tr>
			<% @replies.each do |r| %>
				<%= render :partial => "post_replies/reply", :locals => {:r => r}%>

			<% end %>
			
		</table>
	</div>
	<%= form_for @reply,:url =>post_responses_path(@post), :remote =>true do |f| %>
		<%= render :partial => "post_replies/form", :locals => {:f => f} %>
		
  <%= f.submit "送出回覆" , :class =>"btn btn-primary"%>
 	<%end %>
 	<br>
		
	<div class="fav-post">
		<%= render :partial => 'favorite' %>
	</div>
	<br>
	<%= link_to '發表評論', new_post_response_path(@post) %>
	<br>
	<%= link_to '回首頁' , posts_path %>
	
</div>