config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users 
  resources :posts do
    member do 
      post :favorite
      post :like
    end
    resources :responses, :controller => 'post_replies'
  	collection do
  		get :about
  	end
  end

  get '/switch' => 'users#switch'
  resources :friendships

  namespace :admin do
    resources :groups
    resources :posts do

      collection do
        post :bulk_update
      end
    end
  end

  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "posts#index"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if current_user %>
            Hi, <%=link_to current_user.nickname, user_path(current_user.nickname) %>
            <%= link_to('登出', destroy_user_session_path, :method => :delete) %> 
            <%= link_to('修改密碼', edit_registration_path(:user)) %>
          <% else %>
            <%= link_to('註冊', new_registration_path(:user)) %> 
            <%= link_to('登入', new_session_path(:user)) %>
            <%= link_to "使用Facebook註冊", user_facebook_omniauth_authorize_path %>
          <% end %>
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert">
              <%= flash[:notice] %> 
            </div>
          <% end %>
          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <%= yield %>
          <%= link_to '回首頁' ,posts_path %>
          <% if current_user && current_user.admin? %>
            <%= link_to "admin" , admin_posts_path %>
          <% end %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="container">
        <div class="login pull-left">
          <% if current_user %>
            嗨！ <%=link_to current_user.nickname, user_path(current_user.nickname) %>
          <% else %>
            <%= link_to('註冊', new_registration_path(:user)) %> 
            <%= link_to('登入', new_session_path(:user)) %>    
          <% end %>
        </div>
        <div class="nav pull-right">
          <% if current_user %>
            <%= link_to '關於我', user_path(current_user.nickname) %>  
            <%= link_to('登出', destroy_user_session_path, :method => :delete) %> 
            <%= link_to('修改密碼', edit_registration_path(:user)) %>
          <% end %>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert">
              <%= flash[:notice] %> 
            </div>
          <% end %>
          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <%= yield %>
          <% if current_user && current_user.admin? %>
            <%= link_to "admin" , admin_posts_path %>
          <% end %>

        </div>
      </div>
    </div>
  </body>
  <script>
    $(document).ready(function() {
      $('.group-form').select2();
    })

      


  </script>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForumPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="text-center">
          <div class="col-sm-offset-3 col-sm-6">
            <% if flash[:notice].present? %>
              <div class="alert alert-success" role="alert">
                <%= flash[:notice] %> 
              </div>
            <% end %>
            <% if flash[:alert].present? %>
              <div class="alert alert-danger" role="alert">
                <%= flash[:alert] %>
              </div>
            <% end %>
            <%= yield %>
            <% if current_user && current_user.admin? %>
              <%= link_to "admin" , admin_posts_path %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>


</html>